name: Auto Update Sitemap
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests curl_cffi

      - name: Run script
        run: python purify.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'SitemapBot'
          git config --global user.email 'bot@github.com'
          
          # ИЩЕМ ФАЙЛЫ V4 (которые только что создал Питон)
          if ls sitemap_v5_part*.xml 1> /dev/null 2>&1; then
            git add sitemap_v4_part*.xml
            git commit -m "Update sitemap v4" || echo "No changes to commit"
            git push origin main
          else
            echo "Критическая ошибка: файлы sitemap_v4_part*.xml не найдены!"
            exit 1
          fi
