name: Auto Update Sitemap
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests curl_cffi
      - name: Run script
        run: python purify.py
      - name: Commit and Push
        run: |
          git config --global user.name 'SitemapBot'
          git config --global user.email 'bot@github.com'
          if ls sitemap_final_v1_part*.xml 1> /dev/null 2>&1; then
            git add sitemap_final_v1_part*.xml
            git commit -m "Final XML Fix" || echo "No changes"
            git push origin main
          else
            echo "Error: Files not found"
            exit 1
          fi
