name: Auto Update Sitemap
on:
  schedule:
    - cron: '0 2 * * *' # Запуск каждый день в 2 часа ночи
  workflow_dispatch: # Кнопка ручного запуска

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests curl_cffi

      - name: Run script
        run: python purify.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'SitemapBot'
          git config --global user.email 'bot@github.com'
          
          # Ищем короткие имена sitemap_v3_part...
          if ls sitemap_v3_part*.xml 1> /dev/null 2>&1; then
            git add sitemap_v3_part*.xml
            git commit -m "Update sitemap v3" || echo "No changes to commit"
            git push origin main
          else
            echo "Критическая ошибка: файлы sitemap_v3_part*.xml не найдены!"
            exit 1
          fi
